#!/bin/bash
# Egyszer futtatandó — production secret-ek generálása.
# Az eredményt másold be az .env.prod fájlba.
set -euo pipefail

echo "# ── Generated secrets ($(date +%Y-%m-%d)) ──"
echo "POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '=/+')"
echo "APP_SECRET=$(openssl rand -hex 32)"
echo "JWT_PASSPHRASE=$(openssl rand -base64 32 | tr -d '=/+')"
echo "ENCRYPTION_KEY=$(openssl rand -hex 32)"
echo "OAUTH2_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '=/+')"
echo ""
echo "# OAuth2 RSA kulcspár generálás (futtasd manuálisan):"
echo "# mkdir -p oauth2-keys"
echo "# openssl genrsa -out oauth2-keys/private.key 2048"
echo "# openssl rsa -in oauth2-keys/private.key -pubout -out oauth2-keys/public.key"
echo "# chmod 600 oauth2-keys/private.key"
echo "#"
echo "# Majd másold be a Docker volume-ba:"
echo "# docker cp oauth2-keys/private.key \$(docker compose ps -q api):/var/www/html/config/oauth2/"
echo "# docker cp oauth2-keys/public.key \$(docker compose ps -q api):/var/www/html/config/oauth2/"
echo ""
echo "# JWT kulcspár generálás (futtasd manuálisan a JWT_PASSPHRASE-zel):"
echo "# mkdir -p jwt-keys"
echo "# openssl genpkey -algorithm RSA -out jwt-keys/private.pem \\"
echo "#     -aes256 -pass pass:<JWT_PASSPHRASE> -pkeyopt rsa_keygen_bits:4096"
echo "# openssl rsa -pubout -in jwt-keys/private.pem \\"
echo "#     -passin pass:<JWT_PASSPHRASE> -out jwt-keys/public.pem"
echo "#"
echo "# Majd másold be a Docker volume-ba:"
echo "# docker compose up -d api"
echo "# docker cp jwt-keys/private.pem \$(docker compose ps -q api):/var/www/html/config/jwt/"
echo "# docker cp jwt-keys/public.pem \$(docker compose ps -q api):/var/www/html/config/jwt/"
